# Generated by Django 4.2.11 on 2024-05-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(2, 'appointed'), (1, 'declined')], default=0),
        ),
    ]
